import React, { useState } from "react";
import { VOSviewerOnlineDimensions } from "vosviewer-online/dimensions";

const DATASET_1 = {
  config: null,
  info: {
    description: "",
    title: "",
  },
  network: {
    items: [
      {
        id: "Curriculum And Pedagogy",
        label: "Curriculum And Pedagogy",
        scores: {},
        weights: {},
        cluster: 9,
      },
      {
        id: "students",
        label: "students",
        scores: {},
        weights: {},
        cluster: 21,
      },
      {
        id: "Machine Learning",
        label: "Machine Learning",
        scores: {},
        weights: {},
        cluster: 22,
      },
      {
        id: "neural network",
        label: "neural network",
        scores: {},
        weights: {},
        cluster: 3,
      },
      {
        id: "teachers",
        label: "teachers",
        scores: {},
        weights: {},
        cluster: 14,
      },
      {
        id: "Education Systems",
        label: "Education Systems",
        scores: {},
        weights: {},
        cluster: 14,
      },
      {
        id: "Clinical Sciences",
        label: "Clinical Sciences",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "risk factors",
        label: "risk factors",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "Oncology And Carcinogenesis",
        label: "Oncology And Carcinogenesis",
        scores: {},
        weights: {},
        cluster: 26,
      },
      {
        id: "overall survival",
        label: "overall survival",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "education",
        label: "education",
        scores: {},
        weights: {},
        cluster: 13,
      },
      {
        id: "breast cancer",
        label: "breast cancer",
        scores: {},
        weights: {},
        cluster: 26,
      },
      {
        id: "learning",
        label: "learning",
        scores: {},
        weights: {},
        cluster: 14,
      },
      {
        id: "Linguistics",
        label: "Linguistics",
        scores: {},
        weights: {},
        cluster: 21,
      },
      {
        id: "language",
        label: "language",
        scores: {},
        weights: {},
        cluster: 19,
      },
      {
        id: "Data Management And Data Science",
        label: "Data Management And Data Science",
        scores: {},
        weights: {},
        cluster: 10,
      },
      {
        id: "schools",
        label: "schools",
        scores: {},
        weights: {},
        cluster: 14,
      },
      {
        id: "convolutional neural network",
        label: "convolutional neural network",
        scores: {},
        weights: {},
        cluster: 7,
      },
      {
        id: "Immunology",
        label: "Immunology",
        scores: {},
        weights: {},
        cluster: 18,
      },
      {
        id: "T cells",
        label: "T cells",
        scores: {},
        weights: {},
        cluster: 26,
      },
      {
        id: "control group",
        label: "control group",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "Commercial Law",
        label: "Commercial Law",
        scores: {},
        weights: {},
        cluster: 6,
      },
      {
        id: "law",
        label: "law",
        scores: {},
        weights: {},
        cluster: 20,
      },
      {
        id: "higher education",
        label: "higher education",
        scores: {},
        weights: {},
        cluster: 13,
      },
      {
        id: "Education Policy, Sociology And Philosophy",
        label: "Education Policy, Sociology And Philosophy",
        scores: {},
        weights: {},
        cluster: 13,
      },
      {
        id: "COVID-19",
        label: "COVID-19",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "Strategy, Management And Organisational Behaviour",
        label: "Strategy, Management And Organisational Behaviour",
        scores: {},
        weights: {},
        cluster: 32,
      },
      {
        id: "firms",
        label: "firms",
        scores: {},
        weights: {},
        cluster: 4,
      },
      {
        id: "deep learning",
        label: "deep learning",
        scores: {},
        weights: {},
        cluster: 22,
      },
      {
        id: "Public Law",
        label: "Public Law",
        scores: {},
        weights: {},
        cluster: 29,
      },
      {
        id: "adverse events",
        label: "adverse events",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "Computer Vision And Multimedia Computation",
        label: "Computer Vision And Multimedia Computation",
        scores: {},
        weights: {},
        cluster: 7,
      },
      {
        id: "Nanotechnology",
        label: "Nanotechnology",
        scores: {},
        weights: {},
        cluster: 25,
      },
      {
        id: "nanoparticles",
        label: "nanoparticles",
        scores: {},
        weights: {},
        cluster: 25,
      },
      {
        id: "teaching",
        label: "teaching",
        scores: {},
        weights: {},
        cluster: 14,
      },
      {
        id: "cancer patients",
        label: "cancer patients",
        scores: {},
        weights: {},
        cluster: 26,
      },
      {
        id: "lung cancer",
        label: "lung cancer",
        scores: {},
        weights: {},
        cluster: 26,
      },
      {
        id: "Ecology",
        label: "Ecology",
        scores: {},
        weights: {},
        cluster: 12,
      },
      {
        id: "species",
        label: "species",
        scores: {},
        weights: {},
        cluster: 12,
      },
      {
        id: "progression-free survival",
        label: "progression-free survival",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "Materials Engineering",
        label: "Materials Engineering",
        scores: {},
        weights: {},
        cluster: 24,
      },
      {
        id: "solar cells",
        label: "solar cells",
        scores: {},
        weights: {},
        cluster: 23,
      },
      {
        id: "Internet of Things",
        label: "Internet of Things",
        scores: {},
        weights: {},
        cluster: 11,
      },
      {
        id: "deep neural networks",
        label: "deep neural networks",
        scores: {},
        weights: {},
        cluster: 22,
      },
      {
        id: "mechanical properties",
        label: "mechanical properties",
        scores: {},
        weights: {},
        cluster: 24,
      },
      {
        id: "Language Studies",
        label: "Language Studies",
        scores: {},
        weights: {},
        cluster: 19,
      },
      {
        id: "Distributed Computing And Systems Software",
        label: "Distributed Computing And Systems Software",
        scores: {},
        weights: {},
        cluster: 11,
      },
      {
        id: "skills",
        label: "skills",
        scores: {},
        weights: {},
        cluster: 9,
      },
      {
        id: "Specialist Studies In Education",
        label: "Specialist Studies In Education",
        scores: {},
        weights: {},
        cluster: 31,
      },
      {
        id: "learning process",
        label: "learning process",
        scores: {},
        weights: {},
        cluster: 9,
      },
      {
        id: "lithium-ion batteries",
        label: "lithium-ion batteries",
        scores: {},
        weights: {},
        cluster: 27,
      },
      {
        id: "Applied Mathematics",
        label: "Applied Mathematics",
        scores: {},
        weights: {},
        cluster: 2,
      },
      {
        id: "differential equations",
        label: "differential equations",
        scores: {},
        weights: {},
        cluster: 2,
      },
      {
        id: "school students",
        label: "school students",
        scores: {},
        weights: {},
        cluster: 9,
      },
      {
        id: "Artificial Intelligence",
        label: "Artificial Intelligence",
        scores: {},
        weights: {},
        cluster: 3,
      },
      {
        id: "Crop And Pasture Production",
        label: "Crop And Pasture Production",
        scores: {},
        weights: {},
        cluster: 8,
      },
      {
        id: "yield",
        label: "yield",
        scores: {},
        weights: {},
      },
      {
        id: "cell carcinoma",
        label: "cell carcinoma",
        scores: {},
        weights: {},
        cluster: 26,
      },
      {
        id: "Genetics",
        label: "Genetics",
        scores: {},
        weights: {},
        cluster: 15,
      },
      {
        id: "genes",
        label: "genes",
        scores: {},
        weights: {},
        cluster: 15,
      },
      {
        id: "COVID-19 patients",
        label: "COVID-19 patients",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "companies",
        label: "companies",
        scores: {},
        weights: {},
        cluster: 32,
      },
      {
        id: "Reproductive Medicine",
        label: "Reproductive Medicine",
        scores: {},
        weights: {},
        cluster: 30,
      },
      {
        id: "pregnant women",
        label: "pregnant women",
        scores: {},
        weights: {},
        cluster: 30,
      },
      {
        id: "electrochemical performance",
        label: "electrochemical performance",
        scores: {},
        weights: {},
        cluster: 27,
      },
      {
        id: "rights",
        label: "rights",
        scores: {},
        weights: {},
        cluster: 29,
      },
      {
        id: "magnetic resonance imaging",
        label: "magnetic resonance imaging",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "Physical Chemistry",
        label: "Physical Chemistry",
        scores: {},
        weights: {},
        cluster: 27,
      },
      {
        id: "clinical outcomes",
        label: "clinical outcomes",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "X-ray diffraction",
        label: "X-ray diffraction",
        scores: {},
        weights: {},
        cluster: 27,
      },
      {
        id: "prostate cancer",
        label: "prostate cancer",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "Originality/value",
        label: "Originality/value",
        scores: {},
        weights: {},
        cluster: 32,
      },
      {
        id: "body mass index",
        label: "body mass index",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "Public Health",
        label: "Public Health",
        scores: {},
        weights: {},
        cluster: 28,
      },
      {
        id: "physical activity",
        label: "physical activity",
        scores: {},
        weights: {},
        cluster: 28,
      },
      {
        id: "machine learning",
        label: "machine learning",
        scores: {},
        weights: {},
        cluster: 22,
      },
      {
        id: "Design/methodology/approach",
        label: "Design/methodology/approach",
        scores: {},
        weights: {},
        cluster: 32,
      },
      {
        id: "clinical trials",
        label: "clinical trials",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "Macromolecular And Materials Chemistry",
        label: "Macromolecular And Materials Chemistry",
        scores: {},
        weights: {},
        cluster: 23,
      },
      {
        id: "cohort study",
        label: "cohort study",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "Banking, Finance And Investment",
        label: "Banking, Finance And Investment",
        scores: {},
        weights: {},
        cluster: 4,
      },
      {
        id: "Applied Economics",
        label: "Applied Economics",
        scores: {},
        weights: {},
        cluster: 1,
      },
      {
        id: "market",
        label: "market",
        scores: {},
        weights: {},
        cluster: 4,
      },
      {
        id: "Law In Context",
        label: "Law In Context",
        scores: {},
        weights: {},
        cluster: 20,
      },
      {
        id: "methodology/approach",
        label: "methodology/approach",
        scores: {},
        weights: {},
        cluster: 32,
      },
      {
        id: "immune response",
        label: "immune response",
        scores: {},
        weights: {},
        cluster: 18,
      },
      {
        id: "learning model",
        label: "learning model",
        scores: {},
        weights: {},
        cluster: 22,
      },
      {
        id: "employees",
        label: "employees",
        scores: {},
        weights: {},
        cluster: 32,
      },
      {
        id: "sensor networks",
        label: "sensor networks",
        scores: {},
        weights: {},
        cluster: 10,
      },
      {
        id: "colorectal cancer",
        label: "colorectal cancer",
        scores: {},
        weights: {},
        cluster: 26,
      },
      {
        id: "Historical Studies",
        label: "Historical Studies",
        scores: {},
        weights: {},
        cluster: 17,
      },
      {
        id: "history",
        label: "history",
        scores: {},
        weights: {},
        cluster: 17,
      },
      {
        id: "thin films",
        label: "thin films",
        scores: {},
        weights: {},
        cluster: 24,
      },
      {
        id: "intensive care unit",
        label: "intensive care unit",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "Geology",
        label: "Geology",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "rocks",
        label: "rocks",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "human rights",
        label: "human rights",
        scores: {},
        weights: {},
        cluster: 29,
      },
      {
        id: "COVID-19 pandemic",
        label: "COVID-19 pandemic",
        scores: {},
        weights: {},
        cluster: 9,
      },
      {
        id: "diabetes mellitus",
        label: "diabetes mellitus",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "Agriculture, Land And Farm Management",
        label: "Agriculture, Land And Farm Management",
        scores: {},
        weights: {},
      },
      {
        id: "quality of life",
        label: "quality of life",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "basin",
        label: "basin",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "surface area",
        label: "surface area",
        scores: {},
        weights: {},
        cluster: 27,
      },
    ],
    links: [
      {
        source_id: "Curriculum And Pedagogy",
        strength: 1,
        target_id: "students",
      },
      {
        source_id: "Machine Learning",
        strength: 1,
        target_id: "neural network",
      },
      {
        source_id: "Curriculum And Pedagogy",
        strength: 1,
        target_id: "teachers",
      },
      {
        source_id: "Education Systems",
        strength: 1,
        target_id: "students",
      },
      {
        source_id: "Education Systems",
        strength: 1,
        target_id: "teachers",
      },
      {
        source_id: "Clinical Sciences",
        strength: 1,
        target_id: "risk factors",
      },
      {
        source_id: "Oncology And Carcinogenesis",
        strength: 1,
        target_id: "overall survival",
      },
      {
        source_id: "Curriculum And Pedagogy",
        strength: 1,
        target_id: "education",
      },
      {
        source_id: "Education Systems",
        strength: 1,
        target_id: "education",
      },
      {
        source_id: "Oncology And Carcinogenesis",
        strength: 1,
        target_id: "breast cancer",
      },
      {
        source_id: "Curriculum And Pedagogy",
        strength: 1,
        target_id: "learning",
      },
      {
        source_id: "Linguistics",
        strength: 1,
        target_id: "language",
      },
      {
        source_id: "Data Management And Data Science",
        strength: 1,
        target_id: "neural network",
      },
      {
        source_id: "Curriculum And Pedagogy",
        strength: 1,
        target_id: "schools",
      },
      {
        source_id: "Machine Learning",
        strength: 1,
        target_id: "convolutional neural network",
      },
      {
        source_id: "Clinical Sciences",
        strength: 1,
        target_id: "overall survival",
      },
      {
        source_id: "Immunology",
        strength: 1,
        target_id: "T cells",
      },
      {
        source_id: "Clinical Sciences",
        strength: 1,
        target_id: "control group",
      },
      {
        source_id: "Commercial Law",
        strength: 1,
        target_id: "law",
      },
      {
        source_id: "Education Systems",
        strength: 1,
        target_id: "higher education",
      },
      {
        source_id: "Education Policy, Sociology And Philosophy",
        strength: 1,
        target_id: "education",
      },
      {
        source_id: "Clinical Sciences",
        strength: 1,
        target_id: "COVID-19",
      },
      {
        source_id: "Education Systems",
        strength: 1,
        target_id: "learning",
      },
      {
        source_id: "Strategy, Management And Organisational Behaviour",
        strength: 1,
        target_id: "firms",
      },
      {
        source_id: "Machine Learning",
        strength: 1,
        target_id: "deep learning",
      },
      {
        source_id: "Public Law",
        strength: 1,
        target_id: "law",
      },
      {
        source_id: "Clinical Sciences",
        strength: 1,
        target_id: "adverse events",
      },
      {
        source_id: "Computer Vision And Multimedia Computation",
        strength: 1,
        target_id: "neural network",
      },
      {
        source_id: "Nanotechnology",
        strength: 1,
        target_id: "nanoparticles",
      },
      {
        source_id: "Curriculum And Pedagogy",
        strength: 1,
        target_id: "teaching",
      },
      {
        source_id: "Oncology And Carcinogenesis",
        strength: 1,
        target_id: "cancer patients",
      },
      {
        source_id: "Oncology And Carcinogenesis",
        strength: 1,
        target_id: "lung cancer",
      },
      {
        source_id: "Ecology",
        strength: 1,
        target_id: "species",
      },
      {
        source_id: "Oncology And Carcinogenesis",
        strength: 1,
        target_id: "progression-free survival",
      },
      {
        source_id: "Materials Engineering",
        strength: 1,
        target_id: "solar cells",
      },
      {
        source_id: "Data Management And Data Science",
        strength: 1,
        target_id: "Internet of Things",
      },
      {
        source_id: "Machine Learning",
        strength: 1,
        target_id: "deep neural networks",
      },
      {
        source_id: "Materials Engineering",
        strength: 1,
        target_id: "mechanical properties",
      },
      {
        source_id: "Language Studies",
        strength: 1,
        target_id: "language",
      },
      {
        source_id: "Distributed Computing And Systems Software",
        strength: 1,
        target_id: "Internet of Things",
      },
      {
        source_id: "Curriculum And Pedagogy",
        strength: 1,
        target_id: "skills",
      },
      {
        source_id: "Specialist Studies In Education",
        strength: 1,
        target_id: "students",
      },
      {
        source_id: "Curriculum And Pedagogy",
        strength: 1,
        target_id: "learning process",
      },
      {
        source_id: "Linguistics",
        strength: 1,
        target_id: "students",
      },
      {
        source_id: "Materials Engineering",
        strength: 1,
        target_id: "lithium-ion batteries",
      },
      {
        source_id: "Applied Mathematics",
        strength: 1,
        target_id: "differential equations",
      },
      {
        source_id: "Curriculum And Pedagogy",
        strength: 1,
        target_id: "school students",
      },
      {
        source_id: "Artificial Intelligence",
        strength: 1,
        target_id: "neural network",
      },
      {
        source_id: "Crop And Pasture Production",
        strength: 1,
        target_id: "yield",
      },
      {
        source_id: "Oncology And Carcinogenesis",
        strength: 1,
        target_id: "cell carcinoma",
      },
      {
        source_id: "Genetics",
        strength: 1,
        target_id: "genes",
      },
      {
        source_id: "Clinical Sciences",
        strength: 1,
        target_id: "COVID-19 patients",
      },
      {
        source_id: "Strategy, Management And Organisational Behaviour",
        strength: 1,
        target_id: "companies",
      },
      {
        source_id: "Reproductive Medicine",
        strength: 1,
        target_id: "pregnant women",
      },
      {
        source_id: "Materials Engineering",
        strength: 1,
        target_id: "electrochemical performance",
      },
      {
        source_id: "Education Systems",
        strength: 1,
        target_id: "teaching",
      },
      {
        source_id: "Public Law",
        strength: 1,
        target_id: "rights",
      },
      {
        source_id: "Clinical Sciences",
        strength: 1,
        target_id: "magnetic resonance imaging",
      },
      {
        source_id: "Physical Chemistry",
        strength: 1,
        target_id: "lithium-ion batteries",
      },
      {
        source_id: "Clinical Sciences",
        strength: 1,
        target_id: "clinical outcomes",
      },
      {
        source_id: "Materials Engineering",
        strength: 1,
        target_id: "X-ray diffraction",
      },
      {
        source_id: "Oncology And Carcinogenesis",
        strength: 1,
        target_id: "prostate cancer",
      },
      {
        source_id: "Strategy, Management And Organisational Behaviour",
        strength: 1,
        target_id: "Originality/value",
      },
      {
        source_id: "Clinical Sciences",
        strength: 1,
        target_id: "body mass index",
      },
      {
        source_id: "Public Health",
        strength: 1,
        target_id: "physical activity",
      },
      {
        source_id: "Machine Learning",
        strength: 1,
        target_id: "machine learning",
      },
      {
        source_id: "Data Management And Data Science",
        strength: 1,
        target_id: "convolutional neural network",
      },
      {
        source_id: "Strategy, Management And Organisational Behaviour",
        strength: 1,
        target_id: "Design/methodology/approach",
      },
      {
        source_id: "Clinical Sciences",
        strength: 1,
        target_id: "clinical trials",
      },
      {
        source_id: "Macromolecular And Materials Chemistry",
        strength: 1,
        target_id: "solar cells",
      },
      {
        source_id: "Education Systems",
        strength: 1,
        target_id: "schools",
      },
      {
        source_id: "Clinical Sciences",
        strength: 1,
        target_id: "cohort study",
      },
      {
        source_id: "Banking, Finance And Investment",
        strength: 1,
        target_id: "firms",
      },
      {
        source_id: "Applied Economics",
        strength: 1,
        target_id: "market",
      },
      {
        source_id: "Banking, Finance And Investment",
        strength: 1,
        target_id: "market",
      },
      {
        source_id: "Law In Context",
        strength: 1,
        target_id: "law",
      },
      {
        source_id: "Education Policy, Sociology And Philosophy",
        strength: 1,
        target_id: "higher education",
      },
      {
        source_id: "Strategy, Management And Organisational Behaviour",
        strength: 1,
        target_id: "methodology/approach",
      },
      {
        source_id: "Immunology",
        strength: 1,
        target_id: "immune response",
      },
      {
        source_id: "Machine Learning",
        strength: 1,
        target_id: "learning model",
      },
      {
        source_id: "Physical Chemistry",
        strength: 1,
        target_id: "electrochemical performance",
      },
      {
        source_id: "Strategy, Management And Organisational Behaviour",
        strength: 1,
        target_id: "employees",
      },
      {
        source_id: "Data Management And Data Science",
        strength: 1,
        target_id: "sensor networks",
      },
      {
        source_id: "Computer Vision And Multimedia Computation",
        strength: 1,
        target_id: "convolutional neural network",
      },
      {
        source_id: "Oncology And Carcinogenesis",
        strength: 1,
        target_id: "colorectal cancer",
      },
      {
        source_id: "Oncology And Carcinogenesis",
        strength: 1,
        target_id: "T cells",
      },
      {
        source_id: "Historical Studies",
        strength: 1,
        target_id: "history",
      },
      {
        source_id: "Materials Engineering",
        strength: 1,
        target_id: "thin films",
      },
      {
        source_id: "Clinical Sciences",
        strength: 1,
        target_id: "intensive care unit",
      },
      {
        source_id: "Geology",
        strength: 1,
        target_id: "rocks",
      },
      {
        source_id: "Public Law",
        strength: 1,
        target_id: "human rights",
      },
      {
        source_id: "Clinical Sciences",
        strength: 1,
        target_id: "prostate cancer",
      },
      {
        source_id: "Curriculum And Pedagogy",
        strength: 1,
        target_id: "COVID-19 pandemic",
      },
      {
        source_id: "Physical Chemistry",
        strength: 1,
        target_id: "X-ray diffraction",
      },
      {
        source_id: "Clinical Sciences",
        strength: 1,
        target_id: "diabetes mellitus",
      },
      {
        source_id: "Agriculture, Land And Farm Management",
        strength: 1,
        target_id: "yield",
      },
      {
        source_id: "Clinical Sciences",
        strength: 1,
        target_id: "quality of life",
      },
      {
        source_id: "Geology",
        strength: 1,
        target_id: "basin",
      },
      {
        source_id: "Physical Chemistry",
        strength: 1,
        target_id: "surface area",
      },
      {
        source_id: "Clinical Sciences",
        strength: 1,
        target_id: "progression-free survival",
      },
    ],
  },
};

const DATASET_2 = {
  config: null,
  info: {
    description: "",
    title: "",
  },
  network: {
    items: [
      {
        id: "neural network",
        label: "neural network",
        scores: {},
        weights: {},
      },
      {
        id: "China",
        label: "China",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "overall survival",
        label: "overall survival",
        scores: {},
        weights: {},
        cluster: 15,
      },
      {
        id: "United States",
        label: "United States",
        scores: {},
        weights: {},
        cluster: 2,
      },
      {
        id: "students",
        label: "students",
        scores: {},
        weights: {},
        cluster: 7,
      },
      {
        id: "Indonesia",
        label: "Indonesia",
        scores: {},
        weights: {},
        cluster: 4,
      },
      {
        id: "risk factors",
        label: "risk factors",
        scores: {},
        weights: {},
        cluster: 2,
      },
      {
        id: "electrochemical performance",
        label: "electrochemical performance",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "lithium-ion batteries",
        label: "lithium-ion batteries",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "T cells",
        label: "T cells",
        scores: {},
        weights: {},
        cluster: 15,
      },
      {
        id: "mechanical properties",
        label: "mechanical properties",
        scores: {},
        weights: {},
        cluster: 13,
      },
      {
        id: "breast cancer",
        label: "breast cancer",
        scores: {},
        weights: {},
        cluster: 15,
      },
      {
        id: "control group",
        label: "control group",
        scores: {},
        weights: {},
        cluster: 2,
      },
      {
        id: "solar cells",
        label: "solar cells",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "genes",
        label: "genes",
        scores: {},
        weights: {},
        cluster: 1,
      },
      {
        id: "evolution reaction",
        label: "evolution reaction",
        scores: {},
        weights: {},
        cluster: 14,
      },
      {
        id: "lung cancer",
        label: "lung cancer",
        scores: {},
        weights: {},
        cluster: 15,
      },
      {
        id: "adverse events",
        label: "adverse events",
        scores: {},
        weights: {},
        cluster: 2,
      },
      {
        id: "convolutional neural network",
        label: "convolutional neural network",
        scores: {},
        weights: {},
        cluster: 3,
      },
      {
        id: "India",
        label: "India",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "electrode materials",
        label: "electrode materials",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "progression-free survival",
        label: "progression-free survival",
        scores: {},
        weights: {},
        cluster: 15,
      },
      {
        id: "surface area",
        label: "surface area",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "teachers",
        label: "teachers",
        scores: {},
        weights: {},
        cluster: 7,
      },
      {
        id: "active site",
        label: "active site",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "phylogenetic analysis",
        label: "phylogenetic analysis",
        scores: {},
        weights: {},
        cluster: 8,
      },
      {
        id: "hepatocellular carcinoma",
        label: "hepatocellular carcinoma",
        scores: {},
        weights: {},
        cluster: 15,
      },
      {
        id: "cycling stability",
        label: "cycling stability",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "specific capacity",
        label: "specific capacity",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "specific surface area",
        label: "specific surface area",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "cancer patients",
        label: "cancer patients",
        scores: {},
        weights: {},
        cluster: 15,
      },
      {
        id: "COVID-19",
        label: "COVID-19",
        scores: {},
        weights: {},
        cluster: 2,
      },
      {
        id: "prostate cancer",
        label: "prostate cancer",
        scores: {},
        weights: {},
        cluster: 2,
      },
      {
        id: "high energy density",
        label: "high energy density",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "clinical trials",
        label: "clinical trials",
        scores: {},
        weights: {},
        cluster: 2,
      },
      {
        id: "hydrogen evolution reaction",
        label: "hydrogen evolution reaction",
        scores: {},
        weights: {},
        cluster: 13,
      },
      {
        id: "nanoparticles",
        label: "nanoparticles",
        scores: {},
        weights: {},
        cluster: 14,
      },
      {
        id: "power conversion efficiency",
        label: "power conversion efficiency",
        scores: {},
        weights: {},
        cluster: 12,
      },
      {
        id: "cell carcinoma",
        label: "cell carcinoma",
        scores: {},
        weights: {},
        cluster: 15,
      },
      {
        id: "deep learning",
        label: "deep learning",
        scores: {},
        weights: {},
        cluster: 11,
      },
      {
        id: "learning",
        label: "learning",
        scores: {},
        weights: {},
        cluster: 4,
      },
      {
        id: "oxygen evolution reaction",
        label: "oxygen evolution reaction",
        scores: {},
        weights: {},
        cluster: 13,
      },
      {
        id: "catalytic activity",
        label: "catalytic activity",
        scores: {},
        weights: {},
        cluster: 13,
      },
      {
        id: "gene expression",
        label: "gene expression",
        scores: {},
        weights: {},
        cluster: 8,
      },
      {
        id: "firms",
        label: "firms",
        scores: {},
        weights: {},
        cluster: 17,
      },
      {
        id: "non-small cell lung cancer",
        label: "non-small cell lung cancer",
        scores: {},
        weights: {},
        cluster: 15,
      },
      {
        id: "species",
        label: "species",
        scores: {},
        weights: {},
        cluster: 6,
      },
      {
        id: "cathode materials",
        label: "cathode materials",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "catalyst",
        label: "catalyst",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "protein-coding genes",
        label: "protein-coding genes",
        scores: {},
        weights: {},
        cluster: 8,
      },
      {
        id: "X-ray diffraction",
        label: "X-ray diffraction",
        scores: {},
        weights: {},
        cluster: 13,
      },
      {
        id: "colorectal cancer",
        label: "colorectal cancer",
        scores: {},
        weights: {},
        cluster: 15,
      },
      {
        id: "rate capability",
        label: "rate capability",
        scores: {},
        weights: {},
        cluster: 13,
      },
      {
        id: "deep neural networks",
        label: "deep neural networks",
        scores: {},
        weights: {},
        cluster: 11,
      },
      {
        id: "Internet of Things",
        label: "Internet of Things",
        scores: {},
        weights: {},
        cluster: 5,
      },
      {
        id: "reduction reaction",
        label: "reduction reaction",
        scores: {},
        weights: {},
        cluster: 13,
      },
      {
        id: "Extensive experiments",
        label: "Extensive experiments",
        scores: {},
        weights: {},
        cluster: 11,
      },
      {
        id: "Japan",
        label: "Japan",
        scores: {},
        weights: {},
        cluster: 15,
      },
      {
        id: "perovskite solar cells",
        label: "perovskite solar cells",
        scores: {},
        weights: {},
        cluster: 16,
      },
      {
        id: "immune response",
        label: "immune response",
        scores: {},
        weights: {},
        cluster: 9,
      },
      {
        id: "anode materials",
        label: "anode materials",
        scores: {},
        weights: {},
        cluster: 13,
      },
      {
        id: "genome",
        label: "genome",
        scores: {},
        weights: {},
        cluster: 8,
      },
      {
        id: "water splitting",
        label: "water splitting",
        scores: {},
        weights: {},
        cluster: 13,
      },
      {
        id: "metal-organic frameworks",
        label: "metal-organic frameworks",
        scores: {},
        weights: {},
        cluster: 10,
      },
      {
        id: "clinical outcomes",
        label: "clinical outcomes",
        scores: {},
        weights: {},
        cluster: 2,
      },
    ],
    links: [
      {
        source_id: "neural network",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "overall survival",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "overall survival",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "students",
        strength: 1,
        target_id: "Indonesia",
      },
      {
        source_id: "risk factors",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "neural network",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "electrochemical performance",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "risk factors",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "students",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "lithium-ion batteries",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "T cells",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "electrochemical performance",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "mechanical properties",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "neural network",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "breast cancer",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "control group",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "lithium-ion batteries",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "solar cells",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "genes",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "evolution reaction",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "lung cancer",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "overall survival",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "adverse events",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "breast cancer",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "neural network",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "convolutional neural network",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "neural network",
        strength: 1,
        target_id: "India",
      },
      {
        source_id: "solar cells",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "overall survival",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "electrode materials",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "progression-free survival",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "surface area",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "T cells",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "teachers",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "teachers",
        strength: 1,
        target_id: "Indonesia",
      },
      {
        source_id: "progression-free survival",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "active site",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "phylogenetic analysis",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "surface area",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "convolutional neural network",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "evolution reaction",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "hepatocellular carcinoma",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "cycling stability",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "specific capacity",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "electrode materials",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "specific surface area",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "students",
        strength: 1,
        target_id: "Indonesia",
      },
      {
        source_id: "cancer patients",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "COVID-19",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "prostate cancer",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "high energy density",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "clinical trials",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "specific surface area",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "hydrogen evolution reaction",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "nanoparticles",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "specific capacity",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "power conversion efficiency",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "cell carcinoma",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "cycling stability",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "deep learning",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "convolutional neural network",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "learning",
        strength: 1,
        target_id: "Indonesia",
      },
      {
        source_id: "students",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "oxygen evolution reaction",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "power conversion efficiency",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "teachers",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "T cells",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "catalytic activity",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "genes",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "gene expression",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "firms",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "non-small cell lung cancer",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "solar cells",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "species",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "cathode materials",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "prostate cancer",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "catalyst",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "protein-coding genes",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "evolution reaction",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "X-ray diffraction",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "colorectal cancer",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "neural network",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "rate capability",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "lung cancer",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "cathode materials",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "deep neural networks",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "Internet of Things",
        strength: 1,
        target_id: "India",
      },
      {
        source_id: "high energy density",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "reduction reaction",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "Extensive experiments",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "active site",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "overall survival",
        strength: 1,
        target_id: "Japan",
      },
      {
        source_id: "perovskite solar cells",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "immune response",
        strength: 1,
        target_id: "United States",
      },
      {
        source_id: "anode materials",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "genome",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "water splitting",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "metal-organic frameworks",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "catalyst",
        strength: 1,
        target_id: "China",
      },
      {
        source_id: "clinical outcomes",
        strength: 1,
        target_id: "United States",
      },
    ],
  },
};

const App = () => {
  const [toggle, setToggle] = useState(false);

  return (
    <div>
      <div style={{ margin: "2rem 0" }}>
        <button onClick={() => setToggle(!toggle)}>
          Load a different dataset
        </button>
      </div>
      <div style={{ width: "100%", maxHeight: "500px", height: "50vh" }}>
        <VOSviewerOnlineDimensions
          data={toggle ? DATASET_1 : DATASET_2}
          parameters={{
            largest_component: true,
            looker_ui: true,
            simple_ui: true,
          }}
        />
      </div>
    </div>
  );
};

export default App;
